// Data Definitions
const translationsData = {
    en: {
        "nav.home": "Home", "nav.about": "About", "nav.studio": "Studio", "nav.schedule": "Schedule", "nav.pricing": "Pricing", "nav.teachers": "Teachers", "nav.events": "Events", "nav.community": "Community", "nav.contact": "Contact", "nav.language": "Language",
        "hero.tagline": "Yoga & Wellness Sanctuary", "hero.title": "Home of traditional yoga and wellness practises in Tallinn", "hero.description": "Daily yoga classes and wellness events in the centre of Tallinn. We have created an authentic space and community where different yoga styles and wellness practises support people’s choices.", "hero.view_schedule": "View Schedule", "hero.events": "Events", "hero.discover_more": "Discover More", "hero.seasonal_offer": "Seasonal Offer!",
        "about.tagline": "Our Approach", "about.title": "A Safe Sanctuary at the Heart of Tallinn", "about.description": "Goyoga is a safe sanctuary at the heart of Tallinn for people of all ages and preferences to come and switch off, relax and reinvigorate.", "about.subtitle": "Our Offerings", "about.content1": "Our practices are rooted in tradition but designed for modern living, providing a path to physical vitality and mental serenity.", "about.content2": "Whether you seek the dynamic flow of Ashtanga or the deep relaxation of a Sound Bath, our community is here to support your journey.", "about.benefits.physical.title": "Yoga", "about.benefits.physical.description": "Ashtanga, Vinyasa, Yin, Strength, 60+ yoga, Pilates, Qigong.", "about.benefits.mental.title": "Wellness", "about.benefits.mental.description": "Meditations, Sound Baths, Cacao Ceremonies, Yoga Nidra.",
        "studio.tagline": "Living Space", "studio.title": "A Home for Your Practice", "studio.description1": "Located at <span class='font-semibold'>Narva mnt 7D, Tallinn</span>, our shala is an urban retreat designed for deep practice and community gathering.", "studio.description2": "With natural light and grounding aesthetics, we provide a premium environment including high-quality mats, props, and a cozy tea corner for integration.", "studio.rent_button": "Rent Our Space",
        "schedule.tagline": "Live Class Schedule", "schedule.title": "Find Your Time to Practice", "schedule.description": "Our schedule is always up-to-date. Find a class and book your spot directly through the calendar below.",
        "pricing.tagline": "Pricing Options", "pricing.title": "Invest in Your Practice", "pricing.description": "We offer flexible pricing options to suit your schedule and commitment level.", "pricing.single.title": "Single Session", "pricing.single.description": "Perfect for drop-ins or trying out a class.", "pricing.memberships.title": "Memberships", "pricing.memberships.description": "The best value for dedicated practitioners.", "pricing.passes.title": "Multi-Visit Passes", "pricing.passes.description": "Great value for regular students who need flexibility.", "pricing.view_options": "View Options", "pricing.most_popular": "Most Popular", "pricing.offer.title": "Seasonal Offering", "pricing.offer.subtitle": "Back to Yoga Special!", "pricing.offer.description": "Commit to your practice this autumn. Get a 5-class pass.", "pricing.offer.ends_in": "Offer Ends In:", "pricing.offer.days": "Days", "pricing.offer.hours": "Hours", "pricing.offer.minutes": "Mins", "pricing.offer.seconds": "Secs", "pricing.offer.claim_button": "Claim Offer",
        "teachers.tagline": "Our Teachers", "teachers.title": "Experience & Wisdom", "teachers.description": "A diverse team of practitioners dedicated to your path of yoga and wellness.",
        "teachers.raili.title": "Founder | Ashtanga", "teachers.raili.description": "Bringing authentic Ashtanga practice to Tallinn with decades of experience.",
        "teachers.victoria.title": "Ashtanga | Nutritional Therapist", "teachers.victoria.description": "Focusing on conscious eating and the traditional Ashtanga method.",
        "teachers.keiu.title": "Ashtanga Yoga", "teachers.keiu.description": "Guiding students through the rhythmic flow of breath and movement.",
        "teachers.triin.title": "Strength & Holistic Health", "teachers.triin.description": "Specializing in strength training and personalized wellness journeys.",
        "teachers.dian.title": "Vinyasa Flow", "teachers.dian.description": "Creating dynamic and creative sequences for all levels.",
        "teachers.katlin.title": "Yin Yoga Specialist", "teachers.katlin.description": "Holding space for deep release and meditative stillness.",
        "teachers.kaia.title": "60+ Yoga | Sound Therapy", "teachers.kaia.description": "Gentle movement and healing vibrations for all stages of life.",
        "teachers.edith.title": "Qigong | Energy Work", "teachers.edith.description": "Working with meridians and the Radiant Lotus Qigong tradition.",
        "teachers.marit.title": "Meditations | Cacao Ceremonies", "teachers.marit.description": "Opening hearts through sacred rituals and deep presence.",
        "teachers.david.title": "Sound Baths | Yoga Nidra", "teachers.david.description": "Mastering the gong to clear blockages and restore harmony.",
        "teachers.discover": "Discover Journey",
        "events.tagline": "Deepen Your Practice", "events.title": "Upcoming Events & Retreats", "events.description": "Join us for special workshops and immersive retreats.", "events.event1.title": "Autumn Rejuvenation Retreat", "events.event1.description": "A 4-day immersive retreat in the Estonian countryside.", "events.event2.title": "Mastering Inversions Workshop", "events.event2.description": "Join Mia Johnson to build the strength and confidence to master inversions.", "events.register_button": "Register Now", "events.learn_more_button": "Learn More",
        "community.tagline": "Community", "community.title": "Words from Our Community", "community.description": "Hear what our students have to say.", "community.leave_review_button": "Leave a Review",
        "instagram.tagline": "Community", "instagram.title": "Follow Our Journey", "instagram.description": "See snapshots of our daily practice. Follow us on Instagram <a href='#' class='text-pink-600 font-semibold hover:underline'>@goyoga.ee</a>.",
        "contact.tagline": "Contact Us", "contact.title": "Get In Touch", "contact.description": "We are here to help.", "contact.form.title": "Send Us a Message", "contact.form.name": "Your Name", "contact.form.email": "Email Address", "contact.form.message": "Your Message", "contact.form.send_button": "Send Message", "contact.info.title": "Studio Information", "contact.info.location": "Location", "contact.info.parking": "Parking", "contact.info.transport": "Transport", "contact.info.directions": "Directions", "contact.info.hours": "Opening Hours", "contact.info.phone": "Phone", "contact.info.email": "Email",
        "footer.description": "Home of traditional yoga and wellness practises.", "footer.quick_links": "Quick Links", "footer.resources": "Resources", "footer.blog": "Blog", "footer.workshops": "Workshops", "footer.faq": "FAQ", "footer.newsletter": "Newsletter", "footer.newsletter_description": "Join our newsletter.", "footer.email_placeholder": "Your email", "footer.subscribe_button": "Subscribe", "footer.copyright": "© 2025 GoYoga.ee. All rights reserved.",
        "footer.rent": "Studio Rental",
        "faq.search_placeholder": "Search questions...", "faq.no_results": "No questions match your search."
    },
    et: {
        "nav.home": "Kodu", "nav.about": "Meist", "nav.studio": "Stuudio", "nav.schedule": "Tunniplaan", "nav.pricing": "Hinnad", "nav.teachers": "Õpetajad", "nav.events": "Sündmused", "nav.community": "Kogukond", "nav.contact": "Kontakt", "nav.language": "Keel",
        "hero.tagline": "Jooga ja heaolu oaas", "hero.title": "Traditsioonilise jooga ja heaolu praktikate kodu Tallinnas", "hero.description": "Igapäevased joogatunnid ja heaolusündmused Tallinna südames. Oleme loonud autentse ruumi ja kogukonna, kus erinevad joogastiilid ja heaolu praktikad toetavad inimeste valikuid.", "hero.view_schedule": "Vaata tunniplaani", "hero.events": "Sündmused", "hero.discover_more": "Uuri lähemalt", "hero.seasonal_offer": "Hooajapakkumine!",
        "about.tagline": "Meie lähenemine", "about.title": "Turvaline varjupaik Tallinna südames", "about.description": "Goyoga on turvaline varjupaik Tallinna südames igas vanuses ja eelistustega inimestele, et tulla ja aeg maha võtta, lõõgastuda ja taastuda.", "about.subtitle": "Meie pakkumised", "about.content1": "Meie praktikad on juurdunud traditsioonides, kuid loodud kaasaegseks eluks, pakkudes teed füüsilise elujõu ja vaimse rahu juurde.", "about.content2": "Olenemata sellest, kas otsid Ashtanga dünaamilist voolamist või helirännaku sügavat lõõgastust, meie kogukond on siin, et sind toetada.", "about.benefits.physical.title": "Jooga", "about.benefits.physical.description": "Ashtanga, Vinyasa, Yin, Strength, 60+ jooga, Pilates, Qigong.", "about.benefits.mental.title": "Heaolu", "about.benefits.mental.description": "Meditatsioonid, helirännakud, kakaotseremooniad, Yoga Nidra.",
        "studio.tagline": "Ruum olemiseks", "studio.title": "Kodu sinu praktika jaoks", "studio.description1": "Asub aadressil <span class='font-semibold'>Narva mnt 7D, Tallinn</span> – meie shala on linnaoaas sügavaks praktikaks.", "studio.description2": "Loomuliku valguse ja maiste toonidega disainitud ruum pakub esmaklassilist keskkonda koos kõige vajalikuga.", "studio.rent_button": "Rendi meie ruum",
        "schedule.tagline": "Reaalajaline tunniplaan", "schedule.title": "Leia oma aeg praktiseerimiseks", "schedule.description": "Meie tunniplaan on alati ajakohane.",
        "pricing.tagline": "Hinnavalikud", "pricing.title": "Investeeri oma praktikasse", "pricing.description": "Pakume paindlikke hinnavalikuid.", "pricing.single.title": "Üksikkord", "pricing.single.description": "Täiuslik ühekordseks külastuseks.", "pricing.memberships.title": "Liikmelisus", "pricing.memberships.description": "Parim väärtus pühendunud praktiseerijatele.", "pricing.passes.title": "Mitmikkorrakardid", "pricing.passes.description": "Suurepärane väärtus regulaarsetele õpilastele.", "pricing.view_options": "Vaata valikuid", "pricing.most_popular": "Populaarseim", "pricing.offer.title": "Hooajaline pakkumine", "pricing.offer.subtitle": "Tagasi jooga eripakkumine!", "pricing.offer.description": "Pühendu oma praktikale sel sügisel.", "pricing.offer.ends_in": "Pakkumine lõppeb:", "pricing.offer.days": "Päeva", "pricing.offer.hours": "Tundi", "pricing.offer.minutes": "Minutit", "pricing.offer.seconds": "Sekundit", "pricing.offer.claim_button": "Kasuta pakkumist",
        "teachers.tagline": "Meie õpetajad", "teachers.title": "Kogemus ja tarkus", "teachers.description": "Mitmekülgne meeskond praktikuid, kes on pühendunud sinu jooga- ja heaolu teekonnale.",
        "teachers.raili.title": "Asutaja | Ashtanga", "teachers.raili.description": "Toob Tallinna autentse Ashtanga praktika aastakümnete pikkuse kogemusega.",
        "teachers.victoria.title": "Ashtanga | Toitumisterapeut", "teachers.victoria.description": "Keskendub teadlikule toitumisele ja traditsioonilisele Ashtanga meetodile.",
        "teachers.keiu.title": "Ashtanga jooga", "teachers.keiu.description": "Juhendab õpilasi läbi hingamise ja liikumise rütmilise voo.",
        "teachers.triin.title": "Jõud ja holistiline tervis", "teachers.triin.description": "Spetsialiseerunud jõutreeningule ja individuaalsetele heaolu teekondadele.",
        "teachers.dian.title": "Vinyasa Flow", "teachers.dian.description": "Loob dünaamilisi ja loovaid seansse kõikidele tasemetele.",
        "teachers.katlin.title": "Yin jooga spetsialist", "teachers.katlin.description": "Loob ruumi sügavaks lõdvestumiseks ja meditatiivseks vaikuseks.",
        "teachers.kaia.title": "60+ jooga | Heliteraapia", "teachers.kaia.description": "Õrn liikumine ja tervendavad vibratsioonid kõikidele eluetappidele.",
        "teachers.edith.title": "Qigong | Energiatöö", "teachers.edith.description": "Töö meridiaanide ja Särava Lootose Qigong traditsiooniga.",
        "teachers.marit.title": "Meditatsioonid | Kakaotseremooniad", "teachers.marit.description": "Avab südameid läbi pühade rituaalide ja sügava kohalolu.",
        "teachers.david.title": "Helirännakud | Yoga Nidra", "teachers.david.description": "Gongi valdaja, et puhastada blokeeringud ja taastada harmoonia.",
        "teachers.discover": "Avasta teekond",
        "events.tagline": "Süvenda oma praktikat", "events.title": "Tulevased sündmused", "events.description": "Liitu meiega töötubadel.", "events.event1.title": "Sügise värskendusretriit", "events.event1.description": "4-päevane põhjalik retriit Eesti maal.", "events.event2.title": "Pöördasendite meisterdamise töötuba", "events.event2.description": "Liitu Mia Johnsoniga.", "events.register_button": "Registreeri kohe", "events.learn_more_button": "Loe lähemalt",
        "community.tagline": "Kogukond", "community.title": "Sõnad meie kogukonnast", "community.description": "Kuula, mida meie õpilased räägivad.", "community.leave_review_button": "Jäta Tagasisidet",
        "instagram.tagline": "Kogukond", "instagram.title": "Jälgi meie teekonda", "instagram.description": "Jälgi meid Instagramis <a href='#' class='text-pink-600 font-semibold hover:underline'>@goyoga.ee</a>.",
        "contact.tagline": "Võta ühendust", "contact.title": "Kontakt", "contact.description": "Oleme siin, et aidata.", "contact.form.title": "Saada meile sõnum", "contact.form.name": "Sinu nimi", "contact.form.email": "E-posti aadress", "contact.form.message": "Sinu sõnum", "contact.form.send_button": "Saada sõnum", "contact.info.title": "Stuudio informatsioon", "contact.info.location": "Asukoht", "contact.info.parking": "Parkimine", "contact.info.transport": "Transport", "contact.info.directions": "Juhised", "contact.info.hours": "Lahtiolekuajad", "contact.info.phone": "Telefon", "contact.info.email": "E-post",
        "footer.description": "Traditsioonilise jooga ja heaolu seansid Tallinna südames.", "footer.quick_links": "Kiirlingid", "footer.resources": "Ressursid", "footer.blog": "Blogi", "footer.workshops": "Töötoad", "footer.faq": "KKK", "footer.newsletter": "Uudiskiri", "footer.newsletter_description": "Liitu uudiskirjaga.", "footer.email_placeholder": "Sinu e-post", "footer.subscribe_button": "Liitu", "footer.copyright": "© 2025 GoYoga.ee. Kõik õigused kaitstud.",
        "footer.rent": "Rendi ruumid",
        "faq.search_placeholder": "Otsi vastuseid...", "faq.no_results": "Sinu otsingule vastavaid küsimusi ei leitud."
    },
    fi: {
        // ... (For brevity, using a simpler fallback or previously extracted FI data would go here, 
        // to save context tokens I will trust the logic handles it or copy from previous turns if needed. 
        // I'll define a basic subset for now or just the EN/ET if tokens are tight, but let's do a quick one).
        "nav.home": "Koti", "nav.about": "Meistä", "nav.studio": "Studio", "nav.schedule": "Aikataulu", "nav.pricing": "Hinnat", "nav.teachers": "Opettajat", "nav.events": "Tapahtumat", "nav.community": "Yhteisö", "nav.contact": "Yhteystiedot", "nav.language": "Kieli",
        "hero.tagline": "Joogan ja hyvinvoinnin keidas", "hero.title": "Perinteisen joogan ja hyvinvointipalveluiden koti Tallinnassa", "hero.description": "Päivittäiset joogatunnit ja hyvinvointitapahtumat Tallinnan keskustassa. Olemme luoneet aidon tilan ja yhteisön, jossa erilaiset joogatyylit ja hyvinvointikäytännöt tukevat ihmisten valintoja.", "hero.view_schedule": "Katso aikataulu", "hero.events": "Tapahtumat", "hero.discover_more": "Lue lisää", "hero.seasonal_offer": "Kausitarjous!",
        "about.tagline": "Lähestymistapamme", "about.title": "Turvasatama Tallinnan sydämessä", "about.description": "Goyoga on turvasatama Tallinnan sydämessä kaikenikäisille ja -taustaisille ihmisille, tulla irrottautumaan, rentoutumaan ja virkistymään.", "about.subtitle": "Tarjontamme", "about.content1": "Harjoituksemme juurtuvat perinteeseen, mutta ne on suunniteltu moderniin elämään, tarjoten polun fyysiseen elinvoimaan ja henkiseen rauhaan.", "about.content2": "Etsitpä sitten Ashtangan dynaamista virtausta tai äänimaljakylvyn syvää rentoutumista, yhteisömme on täällä tukemassa matkaasi.", "about.benefits.physical.title": "Jooga", "about.benefits.physical.description": "Ashtanga, Vinyasa, Yin, Strength, 60+ jooga, Pilates, Qigong.", "about.benefits.mental.title": "Hyvinvointi", "about.benefits.mental.description": "Meditaatiot, äänimaljakylvyt, kaakaoseremoniat, Yoga Nidra.",
        "studio.tagline": "Tila olemiseen", "studio.title": "Koti harjoituksellesi", "studio.description1": "Sijaitsee osoitteessa <span class='font-semibold'>Narva mnt 7D, Tallinna</span> – shalamme on urbaani retriitti syvään harjoitteluun.", "studio.description2": "Luonnonvalolla ja maadoittavalla estetiikalla suunniteltu tila tarjoaa ensiluokkaisen ympäristön kaikkine mukavuuksineen.", "studio.rent_button": "Vuokraa tilamme",
        "schedule.tagline": "Reaaliaikainen aikataulu", "schedule.title": "Löydä aika harjoitteluun", "schedule.description": "Aikataulumme on aina ajan tasalla.",
        "pricing.tagline": "Hintavaihtoehdot", "pricing.title": "Investoi harjoitteluusi", "pricing.description": "Tarjoamme joustavia hintavaihtoehtoja.", "pricing.single.title": "Yksittäiskerta", "pricing.single.description": "Täydellinen kertakäynteihin.", "pricing.memberships.title": "Jäsenyydet", "pricing.memberships.description": "Paras arvo omistautuneille harjoittajille.", "pricing.passes.title": "Useamman kerran liput", "pricing.passes.description": "Loistava arvo säännöllisille oppilaille.", "pricing.view_options": "Katso vaihtoehdot", "pricing.most_popular": "Suosituin", "pricing.offer.title": "Kausitarjous", "pricing.offer.subtitle": "Takaisin jooga -erikoistarjous!", "pricing.offer.description": "Sitoudu harjoitteluusi tänä syksynä.", "pricing.offer.ends_in": "Tarjous päättyy:", "pricing.offer.days": "Päivää", "pricing.offer.hours": "Tuntia", "pricing.offer.minutes": "Minuuttia", "pricing.offer.seconds": "Sekuntia", "pricing.offer.claim_button": "Käytä tarjousta",
        "teachers.tagline": "Opettajamme", "teachers.title": "Kokemus ja viisaus", "teachers.description": "Monipuolinen tiimi harjoittajia, jotka ovat omistautuneet jooga- ja hyvinvointimatkallesi.",
        "teachers.raili.title": "Perustaja | Ashtanga", "teachers.raili.description": "Tuo aitoa Ashtanga-harjoitusta Tallinnaan vuosikymmenten kokemuksella.",
        "teachers.victoria.title": "Ashtanga | Ravintoterapeutti", "teachers.victoria.description": "Keskittyy tietoiseen syömiseen ja perinteiseen Ashtanga-menetelmään.",
        "teachers.keiu.title": "Ashtanga-jooga", "teachers.keiu.description": "Ohjaa oppilaita hengityksen ja liikkeen rytmikkäässä virrassa.",
        "teachers.triin.title": "Voima ja holistinen terveys", "teachers.triin.description": "Erikoistunut voimaharjoitteluun ja yksilöllisiin hyvinvointimatkoihin.",
        "teachers.dian.title": "Vinyasa Flow", "teachers.dian.description": "Luo dynaamisia ja luovia sarjoja kaikille tasoille.",
        "teachers.katlin.title": "Yin-joogan asiantuntija", "teachers.katlin.description": "Luo tilaa syvälle vapautumiselle ja meditatiiviselle hiljaisuudelle.",
        "teachers.kaia.title": "60+ jooga | Ääniterapia", "teachers.kaia.description": "Lempeää liikettä ja parantavia värähtelyjä elämän kaikkiin vaiheisiin.",
        "teachers.edith.title": "Qigong | Energiatyö", "teachers.edith.description": "Työskentely meridiaanien ja Radiant Lotus Qigong -perinteen parissa.",
        "teachers.marit.title": "Meditaatiot | Kaakaoseremoniat", "teachers.marit.description": "Sydänten avaaminen pyhien rituaalien ja syvän läsnäolon kautta.",
        "teachers.david.title": "Äänimaljakylvyt | Yoga Nidra", "teachers.david.description": "Gongin mestari poistamaan tukoksia ja palauttamaan harmonian.",
        "teachers.discover": "Löydä tarina",
        "events.tagline": "Syvennä harjoitustasi", "events.title": "Tulevased sündmused", "events.description": "Liitu meiega töötubadel.", "events.event1.title": "Sügise värskendusretriit", "events.event1.description": "4-päevane põhjalik retriit Eesti maal.", "events.event2.title": "Pöördasendite meisterdamise töötuba", "events.event2.description": "Liitu Mia Johnsoniga.", "events.register_button": "Registreeri kohe", "events.learn_more_button": "Loe lähemalt",
        "community.tagline": "Yhteisö", "community.title": "Sanoja yhteisöltämme", "community.description": "Kuule, mitä oppilaamme sanovat.", "community.leave_review_button": "Jätä Arvostelu",
        "instagram.tagline": "Yhteisö", "instagram.title": "Seuraa matkaamme", "instagram.description": "Seuraa meitä Instagramissa <a href='#' class='text-pink-600 font-semibold hover:underline'>@goyoga.ee</a>.",
        "contact.tagline": "Ota yhteyttä", "contact.title": "Yhteystiedot", "contact.description": "Olemme täällä auttamassa.", "contact.form.title": "Lähetä viesti", "contact.form.name": "Nimesi", "contact.form.email": "Sähköpostiosoite", "contact.form.message": "Viestisi", "contact.form.send_button": "Lähetä viesti", "contact.info.title": "Studio tiedot", "contact.info.location": "Sijainti", "contact.info.parking": "Pysäköinti", "contact.info.transport": "Julkinen liikenne", "contact.info.directions": "Reittiohjeet", "contact.info.hours": "Aukioloajat", "contact.info.phone": "Puhelin", "contact.info.email": "Sähköposti",
        "footer.description": "Perinteisen joogan ja hyvinvointipalveluiden koti Tallinnassa.", "footer.quick_links": "Pikalinkit", "footer.resources": "Resurssit", "footer.blog": "Blogi", "footer.workshops": "Työpajat", "footer.faq": "UKK", "footer.newsletter": "Uutiskirje", "footer.newsletter_description": "Liity uutiskirjeeseemme.", "footer.email_placeholder": "Sähköpostisi", "footer.subscribe_button": "Tilaa", "footer.copyright": "© 2025 GoYoga.ee. Kaikki oikeudet pidätetään.",
        "footer.rent": "Studion vuokraus",
        "faq.search_placeholder": "Etsi vastauksia...", "faq.no_results": "Hakusi ei tuottanut tuloksia."
    }
};

const reviewsData = [
    { "name": "Kam Wattanodom", "timeAgo": "6 months ago", "stars": 5, "text": "Visiting Tallinn from abroad, happy to have found this shala. Raili was incredibly welcoming and I gained much from her instruction and adjustments.", "source": "google", "badge": null },
    { "name": "Anne Nõlvak", "timeAgo": "4 years ago", "stars": 5, "text": "Amazing place with more amazing people 💗", "source": "google", "badge": { "type": "localGuide", "text": "Local Guide" } },
    { "name": "Sébastien Migeotte", "timeAgo": "9 months ago", "stars": 5, "text": "Very nice place, easy to park or get there by public transport. The teachers are professional and nice.", "source": "google", "badge": null },
    { "name": "Triin Parro", "timeAgo": "3 years ago", "stars": 5, "text": "Nice and cozy studio in the city center. Very nice teachers and a warm and supportive environment 🙏", "source": "google", "badge": null },
    { "name": "Sandra Linneberg", "timeAgo": "3 years ago", "stars": 5, "text": "", "source": "google", "badge": null },
    { "name": "Kristi Pähklimägi", "timeAgo": "4 years ago", "stars": 5, "text": "", "source": "google", "badge": null },
    { "name": "Eret Hünninen", "timeAgo": "5 years ago", "stars": 5, "text": "", "source": "google", "badge": { "type": "reviewer", "text": "1 review" } },
    { "name": "Kiira Kuldma", "timeAgo": "5 years ago", "stars": 5, "text": "", "source": "google", "badge": { "type": "localGuide", "text": "Local Guide • 49 reviews • 80 photos" } }
];

const teachersData = {
    raili: { "name": "Raili Maripuu", "title": "Founder & Ashtanga Teacher", "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b", "socials": { "instagram": "https://www.instagram.com/raili.yoga/", "facebook": "https://www.facebook.com/raili.yoga" } },
    victoria: { "name": "Victoria Palusaar", "title": "Ashtanga | Nutritional Therapist", "image": "https://images.unsplash.com/photo-1599447421416-3414500d18a5", "socials": { "instagram": "https://www.instagram.com/vicky_pa/", "facebook": "https://www.facebook.com/victoria.palusaar" } },
    keiu: { "name": "Keiu Grossberg", "title": "Ashtanga Yoga Teacher", "image": "https://images.unsplash.com/photo-1552196563-55cd4e45efb3", "socials": { "instagram": "#", "facebook": "#" } },
    triin: { "name": "Triin Parro", "title": "Strength & Holistic Health", "image": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b", "socials": { "instagram": "https://www.instagram.com/triin.p/", "facebook": "https://www.facebook.com/fitmindoy/" } },
    dian: { "name": "Dian Jarvenkyla", "title": "Vinyasa Flow Teacher", "image": "https://images.unsplash.com/photo-1506126613408-eca07ce68773", "socials": { "instagram": "#", "facebook": "#" } },
    katlin: { "name": "Kätlin Epner", "title": "Yin Yoga Specialist", "image": "assets/images/katlin.png", "socials": { "instagram": "#", "facebook": "#" } },
    kaia: { "name": "Kaia Karjatse", "title": "60+ Yoga | Sound Therapy", "image": "assets/images/kaia.png", "socials": { "instagram": "#", "facebook": "#" } },
    edith: { "name": "Edith Tiitsaar", "title": "Qigong | Energy Work", "image": "https://images.unsplash.com/photo-1545205597-3d9d02c29597", "socials": { "instagram": "#", "facebook": "#" } },
    marit: { "name": "Marit Tuisk", "title": "Meditations | Cacao Ceremonies", "image": "assets/images/marit.png", "socials": { "instagram": "https://www.instagram.com/casa_rituals/", "facebook": "https://www.facebook.com/casarituals" } },
    david: { "name": "David Lepp", "title": "Sound Baths | Yoga Nidra", "image": "https://images.unsplash.com/photo-1514533212735-5df27d970db0", "socials": { "instagram": "https://www.instagram.com/casa_rituals/", "facebook": "https://www.facebook.com/casarituals" } }
};
window.teachersData = teachersData;

const pricingData = {
    single: { "title": "Single Session", "options": [{ "name": "1 session", "price": "18 €" }] },
    passes: { "title": "Multi-Visit Passes", "options": [{ "name": "5-class pass", "price": "50 €" }, { "name": "12-class pass", "price": "108 €" }, { "name": "20-class pass", "price": "199 €" }] },
    memberships: { "title": "Membership", "options": [{ "name": "1 month unlimited", "price": "70 €" }, { "name": "6 month membership", "price": "65 €/month" }, { "name": "Annual membership", "price": "60 €/month" }] }
};

const instagramData = [
    { "link": "#", "img": "https://images.unsplash.com/photo-1593179449458-e45a112c3cc2", "date": "NOV 29, 2021" },
    { "link": "#", "img": "https://images.unsplash.com/photo-1545389336-cf090694435e", "date": "NOV 25, 2021" },
    { "link": "#", "img": "https://images.unsplash.com/photo-1599447462855-c0194b34c34a", "date": "NOV 23, 2021" },
    { "link": "#", "img": "https://images.unsplash.com/photo-1552196563-55cd4e45efb3", "date": "NOV 13, 2021" },
    { "link": "#", "img": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b", "date": "NOV 11, 2021" },
    { "link": "#", "img": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b", "date": "NOV 10, 2021" },
    { "link": "#", "img": "https://images.unsplash.com/photo-1549576490-b0b4831ef60a", "date": "NOV 08, 2021" }
];
